/* This file was generated by Ragel. Your edits will be lost.
 *
 * This is a state machine implementation of String#unpack.
 *
 * vim: filetype=cpp
 */

#include "vm.hpp"
#include "object_utils.hpp"

#include "builtin/array.hpp"
#include "builtin/string.hpp"

namespace rubinius {
  Array* String::unpack(STATE, String* directives) {
    return force_as<Array>(Primitives::failure());
  }
}
